name: Build and upload binaries to release
on:
  push:
    branches:
      - "main"

jobs:
  manifest:
    name: Release manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload manifest to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: manifest.json
          asset_name: manifest.json
          tag: ${{ github.ref }}
          overwrite: true
          body: "Override manifest"
